/*
 * File: app/view/AboutPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contacts.view.AboutPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.aboutpanel',

    requires: [
        'Ext.TitleBar',
        'Ext.Img'
    ],

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'За автора'
            },
            {
                xtype: 'image',
                height: 201,
                src: 'resources/images/logo.png'
            },
            {
                xtype: 'image',
                height: 201,
                src: 'resources/images/author.png'
            }
        ]
    }

});